# Generated by Django 2.1.7 on 2019-03-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deleter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInboxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Входящий документ',
                'verbose_name_plural': 'Входящие документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentOutboxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Исходящий документ',
                'verbose_name_plural': 'Исходящие документы',
                'ordering': ('-title',),
            },
        ),
        migrations.CreateModel(
            name='UTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
