# Generated by Django 2.1.7 on 2019-03-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deleter', '0002_auto_20190327_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utm',
            old_name='addres',
            new_name='address',
        ),
    ]
